config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  root 'logs#index'
  resources :processings, only: [:new, :create]
  resources :processed_logs
  resources :logs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,
    only: [:sessions],
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }
end

app/models/processed_log.rb
# == Schema Information
#
# Table name: processed_logs
#
#  id             :integer          not null, primary key
#  all_phase_done :boolean
#  content        :text
#  phase          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  log_id         :integer
#
# Indexes
#
#  index_processed_logs_on_log_id  (log_id)
#

class ProcessedLog < ApplicationRecord
  has_paper_trail

  belongs_to :log, inverse_of: :processed_logs
end

app/controllers/processed_logs_controller.rb
class ProcessedLogsController < ApplicationController
  authorize_resource

  before_action :set_processed_log, only: [:show, :edit, :update, :destroy]

  # GET /processed_logs
  # GET /processed_logs.json
  def index
    @processed_logs = ProcessedLog.all
  end

  # GET /processed_logs/1
  # GET /processed_logs/1.json
  def show
  end

  # GET /processed_logs/new
  def new
    @processed_log = ProcessedLog.new
  end

  # GET /processed_logs/1/edit
  def edit
  end

  # POST /processed_logs
  # POST /processed_logs.json
  def create
    @processed_log = ProcessedLog.new(processed_log_params)

    respond_to do |format|
      if @processed_log.save
        format.html { redirect_to @processed_log, notice: 'Processed log was successfully created.' }
        format.json { render :show, status: :created, location: @processed_log }
      else
        format.html { render :new }
        format.json { render json: @processed_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /processed_logs/1
  # PATCH/PUT /processed_logs/1.json
  def update
    respond_to do |format|
      if @processed_log.update(processed_log_params)
        format.html { redirect_to @processed_log, notice: 'Processed log was successfully updated.' }
        format.json { render :show, status: :ok, location: @processed_log }
      else
        format.html { render :edit }
        format.json { render json: @processed_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /processed_logs/1
  # DELETE /processed_logs/1.json
  def destroy
    @processed_log.destroy
    respond_to do |format|
      format.html { redirect_to processed_logs_url, notice: 'Processed log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_processed_log
      @processed_log = ProcessedLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def processed_log_params
      params.require(:processed_log).permit(:phase, :all_phase_done)
    end
end

app/helpers/processed_logs_helper.rb
module ProcessedLogsHelper
end

app/views/processed_logs/_form.html.erb
<%= form_with(model: processed_log, local: true) do |form| %>
  <% if processed_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(processed_log.errors.count, "error") %> prohibited this processed_log from being saved:</h2>

      <ul>
      <% processed_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :phase %>
    <%= form.text_field :phase %>
  </div>

  <div class="field">
    <%= form.label :all_phase_done %>
    <%= form.check_box :all_phase_done %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/processed_logs/edit.html.erb
<h1>Editing Processed Log</h1>

<%= render 'form', processed_log: @processed_log %>

<%= link_to 'Show', @processed_log %> |
<%= link_to 'Back', processed_logs_path %>

app/views/processed_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Processed Logs</h1>

<table>
  <thead>
    <tr>
      <th>Phase</th>
      <th>All phase done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @processed_logs.each do |processed_log| %>
      <tr>
        <td><%= processed_log.phase %></td>
        <td><%= processed_log.all_phase_done %></td>
        <td><%= link_to 'Show', processed_log %></td>
        <td><%= link_to 'Edit', edit_processed_log_path(processed_log) %></td>
        <td><%= link_to 'Destroy', processed_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Processed Log', new_processed_log_path %>

app/views/processed_logs/new.html.erb
<h1>New Processed Log</h1>

<%= render 'form', processed_log: @processed_log %>

<%= link_to 'Back', processed_logs_path %>

app/views/processed_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phase:</strong>
  <%= @processed_log.phase %>
</p>

<p>
  <strong>All phase done:</strong>
  <%= @processed_log.all_phase_done %>
</p>

<p>
  <strong>Content:</strong>
  <pre><%= @processed_log.content %></pre>
</p>

<p>
  <strong>Originator:</strong>
  <%= @processed_log.paper_trail.originator %>
</p>

<%= link_to 'Edit', edit_processed_log_path(@processed_log) %> |
<%= link_to 'Back', processed_logs_path %>